### ISSUE TITLE
it stays loading victim options

### ISSUE THREAD

**Issue by Storm8lack** [anirudhmalik/xhunter#33]
the application presents an error when opening the different options of the victim, it keeps loading the information and does not show anything.

https://user-images.githubusercontent.com/108852442/180363852-c690a5f4-eb94-4c05-b23f-03df0b501f4d.mp4

**Comment by HeatWavve** [comment]
@Storm8lack Since required permission are not granted you wont be able to see the data.

**Comment by Storm8lack** [comment]
> @Storm8lackDado que no se otorgan los permisos necesarios, no podrá ver los datos.

ok... that's what I figured, we have to wait for them to add the permissions feature to the payload.

**Comment by HeatWavve** [comment]
You can manually add permission to apk by decompiling

**Comment by anirudhmalik** [comment]
Injecting permission feature is in testing, since we need to decompile full apk including resources of app which is compatible with all android version but problem is to build that apk back we need `aapt/aapt2` binaries which is officially available for other platforms like windows, linux and mac except android. So I have compiled those binaries for android from the source code which has been tested on android 9 and 10. It ran good without any error and soon be available in upcoming release.
Hope you might understood the real deal here.

**Comment by anirudhmalik** [comment]
@Storm8lack you are using localtunnel server which is extremely slow sometimes and also when victim won't allow permission you be notified when you click on required feature options.

**Comment by Storm8lack** [comment]
> La función de permiso de inyección está en prueba, ya que necesitamos descompilar el apk completo, incluidos los recursos de la aplicación que es compatible con todas las versiones de Android, pero el problema es volver a compilar ese apk. Necesitamos `aapt/aapt2`archivos binarios que estén disponibles oficialmente para otras plataformas como Windows, Linux y Mac, excepto androide. Así que compilé esos binarios para Android a partir del código fuente que se probó en Android 9 y 10. Funcionó bien sin ningún error y pronto estará disponible en la próxima versión. Espero que hayas entendido el verdadero negocio aquí.

ok I understand

**Comment by Storm8lack** [comment]
> Puede agregar manualmente permisos a apk descompilando

can you tell me how to add it manually
